log:
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

mint_tracker:
  initial_block: 0
  iteration_size: 100
  runner: # Periods settings
    normal_period: 10s
    min_abnormal_period: 10s
    max_abnormal_period: 10s
  contracts:
    - 0x32C43cd0edF92C7D6C731Ce699798592f36A1Cc3
    - 0x3bD908CaE172Bd4b37DdF0D69b05C09d75631B36

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: 
  service_port: 80
