log:
  level: debug
  disable_sentry: true

db:
  url: postgres://tracker:tracker@localhost:9483/tracker?sslmode=disable

listener:
  addr: :7687

ethereum_client: # Rpc and WS addresses
  rpc: https://rpc.goerli.mudit.blog/
  web_socket: https://rpc.goerli.mudit.blog/

factory_tracker:
  name: factory_tracker # Name to be displayed in logs
  address: 0xE05AD5fcE7f3F8EA8D85BC180a0d738D30daBfFb
  runner: # Periods settings
    normal_period: 10s
    min_abnormal_period: 10s
    max_abnormal_period: 10s
  first_block: 10  # A block to begin from
  iteration_size: 100

mint_tracker:
  name: mint_tracker # Name to be displayed in logs
  capacity: 1
  iteration_size: 100

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: 
  service_port: 80
