log:
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

ethereum_client: # Rpc and WS addresses
  rpc: https://rpc.evm.testnet.moonrabbit.com
  web_socket: ws://104.248.111.251:9944

factory_tracker:
  address: 0xE05AD5fcE7f3F8EA8D85BC180a0d738D30daBfFb
  runner: # Periods settings
    normal_period: 10s
    min_abnormal_period: 10s
    max_abnormal_period: 10s
  first_block: 564400  # A block to begin from
  iteration_size: 100

mint_tracker:
  capacity: 1
  iteration_size: 100

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: 
  service_port: 80
