-- +migrate Up

ALTER TABLE IF EXISTS contracts
    ADD COLUMN IF NOT EXISTS chain_id BIGINT NOT NULL DEFAULT 5; -- TODO: SET POLYGON CHAIN_ID (137)

-- +migrate Down

ALTER TABLE IF EXISTS contracts
    DROP COLUMN IF EXISTS chain_id;
